JPERF-941: Fix branch tracking in Git fixtures
Fixes the `ReleaseTest`, which was failing with:
```
pl.allegro.tech.build.axion.release.domain.scm.ScmException: Branch refs/heads/master is not set to track another branch
```
The jgit API doesn't have equivalents for:
* `git branch --set-upstream-to`
* `git push --set-upstream`

So we edit the repo config directly, as per https://stackoverflow.com/a/27825315